package coincheck

import (
	coincheckgo "github.com/Akagi201/coincheckgo"
)

//type AutoGenerated struct {
//	Success       bool   `json:"success"`
//	Jpy           string `json:"jpy"`
//	Btc           string `json:"btc"`
//	Eth           string `json:"eth"`
//	Etc           string `json:"etc"`
//	Lsk           string `json:"lsk"`
//	Fct           string `json:"fct"`
//	Xrp           string `json:"xrp"`
//	Xem           string `json:"xem"`
//	Ltc           string `json:"ltc"`
//	Bch           string `json:"bch"`
//	Mona          string `json:"mona"`
//	Xlm           string `json:"xlm"`
//	Qtum          string `json:"qtum"`
//	Bat           string `json:"bat"`
//	Iost          string `json:"iost"`
//	Enj           string `json:"enj"`
//	Omg           string `json:"omg"`
//	Plt           string `json:"plt"`
//	Xym           string `json:"xym"`
//	JpyReserved   string `json:"jpy_reserved"`
//	BtcReserved   string `json:"btc_reserved"`
//	EthReserved   string `json:"eth_reserved"`
//	EtcReserved   string `json:"etc_reserved"`
//	LskReserved   string `json:"lsk_reserved"`
//	FctReserved   string `json:"fct_reserved"`
//	XrpReserved   string `json:"xrp_reserved"`
//	XemReserved   string `json:"xem_reserved"`
//	LtcReserved   string `json:"ltc_reserved"`
//	BchReserved   string `json:"bch_reserved"`
//	MonaReserved  string `json:"mona_reserved"`
//	XlmReserved   string `json:"xlm_reserved"`
//	QtumReserved  string `json:"qtum_reserved"`
//	BatReserved   string `json:"bat_reserved"`
//	IostReserved  string `json:"iost_reserved"`
//	EnjReserved   string `json:"enj_reserved"`
//	OmgReserved   string `json:"omg_reserved"`
//	PltReserved   string `json:"plt_reserved"`
//	XymReserved   string `json:"xym_reserved"`
//	JpyLendInUse  string `json:"jpy_lend_in_use"`
//	BtcLendInUse  string `json:"btc_lend_in_use"`
//	EthLendInUse  string `json:"eth_lend_in_use"`
//	EtcLendInUse  string `json:"etc_lend_in_use"`
//	LskLendInUse  string `json:"lsk_lend_in_use"`
//	FctLendInUse  string `json:"fct_lend_in_use"`
//	XrpLendInUse  string `json:"xrp_lend_in_use"`
//	XemLendInUse  string `json:"xem_lend_in_use"`
//	LtcLendInUse  string `json:"ltc_lend_in_use"`
//	BchLendInUse  string `json:"bch_lend_in_use"`
//	MonaLendInUse string `json:"mona_lend_in_use"`
//	XlmLendInUse  string `json:"xlm_lend_in_use"`
//	QtumLendInUse string `json:"qtum_lend_in_use"`
//	BatLendInUse  string `json:"bat_lend_in_use"`
//	IostLendInUse string `json:"iost_lend_in_use"`
//	EnjLendInUse  string `json:"enj_lend_in_use"`
//	OmgLendInUse  string `json:"omg_lend_in_use"`
//	PltLendInUse  string `json:"plt_lend_in_use"`
//	XymLendInUse  string `json:"xym_lend_in_use"`
//	JpyLent       string `json:"jpy_lent"`
//	BtcLent       string `json:"btc_lent"`
//	EthLent       string `json:"eth_lent"`
//	EtcLent       string `json:"etc_lent"`
//	LskLent       string `json:"lsk_lent"`
//	FctLent       string `json:"fct_lent"`
//	XrpLent       string `json:"xrp_lent"`
//	XemLent       string `json:"xem_lent"`
//	LtcLent       string `json:"ltc_lent"`
//	BchLent       string `json:"bch_lent"`
//	MonaLent      string `json:"mona_lent"`
//	XlmLent       string `json:"xlm_lent"`
//	QtumLent      string `json:"qtum_lent"`
//	BatLent       string `json:"bat_lent"`
//	IostLent      string `json:"iost_lent"`
//	EnjLent       string `json:"enj_lent"`
//	OmgLent       string `json:"omg_lent"`
//	PltLent       string `json:"plt_lent"`
//	XymLent       string `json:"xym_lent"`
//	JpyDebt       string `json:"jpy_debt"`
//	BtcDebt       string `json:"btc_debt"`
//	EthDebt       string `json:"eth_debt"`
//	EtcDebt       string `json:"etc_debt"`
//	LskDebt       string `json:"lsk_debt"`
//	FctDebt       string `json:"fct_debt"`
//	XrpDebt       string `json:"xrp_debt"`
//	XemDebt       string `json:"xem_debt"`
//	LtcDebt       string `json:"ltc_debt"`
//	BchDebt       string `json:"bch_debt"`
//	MonaDebt      string `json:"mona_debt"`
//	XlmDebt       string `json:"xlm_debt"`
//	QtumDebt      string `json:"qtum_debt"`
//	BatDebt       string `json:"bat_debt"`
//	IostDebt      string `json:"iost_debt"`
//	EnjDebt       string `json:"enj_debt"`
//	OmgDebt       string `json:"omg_debt"`
//	PltDebt       string `json:"plt_debt"`
//	XymDebt       string `json:"xym_debt"`
//}

func NEW(key, secret string) coincheckgo.CoinCheck {
	client := new(coincheckgo.CoinCheck).NewClient(key, secret)
	return client
}

func GetBalance(key, secret string) string {
	balance := NEW(key, secret).Account.Balance()
	return balance
}
